# Generated by Django 6.0.5 on 2026-05-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_portfolio_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('salon', 'Salon'), ('barbershop', 'Barbershop'), ('nail_tech', 'Nail Tech'), ('spa', 'Spa'), ('lash_studio', 'Lash Studio'), ('makeup_artist', 'Makeup Artist')], default='salon', max_length=20),
        ),
    ]
