# Generated by Django 6.0.5 on 2026-05-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('bookings', '0004_appointmenthistory_appointment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentlog',
            index=models.Index(fields=['created_at', 'agent_type'], name='agentlog_created_type_idx'),
        ),
    ]
