# Generated by Django 6.0.5 on 2026-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('booking', 'Booking'), ('scheduling', 'Scheduling'), ('payment', 'Payment'), ('insights', 'Insights'), ('onboarding', 'Onboarding')], max_length=20)),
                ('action', models.TextField()),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending_human', 'Pending Human')], max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
