# Generated by Django 6.0.5 on 2026-05-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('hair', 'Hair'), ('nails', 'Nails'), ('braids', 'Braids'), ('colour', 'Colour'), ('lashes', 'Lashes'), ('other', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price_zmw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_zmw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buffer_minutes', models.PositiveIntegerField(default=0, help_text='Clean-up / prep time appended after the appointment slot.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='services.service')),
            ],
        ),
    ]
