# Generated by Django 6.0.5 on 2026-05-09 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffservice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price_zmw__gte', 0)), name='service_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_zmw__lte', models.F('price_zmw'))), name='service_deposit_le_price'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff', 'service'), name='staffservice_staff_service_uniq'),
        ),
    ]
