# Generated by Django 6.0.5 on 2026-05-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_zmw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance'), ('refund', 'Refund')], max_length=10)),
                ('method', models.CharField(choices=[('airtel_money', 'Airtel Money'), ('mtn_momo', 'MTN MoMo'), ('card', 'Card'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('dpo_transaction_id', models.CharField(blank=True, max_length=100)),
                ('dpo_token', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.appointment')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
