# Generated by Django 6.0.5 on 2026-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_workinghours_unique_together_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
