# Generated by Django 6.0.5 on 2026-05-09 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='bookings.customer'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='bookings.customer'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='preferred_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['starts_at'], name='appt_starts_at_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['ends_at'], name='appt_ends_at_idx'),
        ),
    ]
